name: Deploy ML Model to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: vetion-app-424904
  SERVICE: model-vetion-app
  REGION: asia-southeast2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download ML Model
        run: |
          mkdir -p model
          wget -q https://github.com/VetionTeam/Vetion-Model/raw/main/MyModel%20%281%29.h5 -O model/MyModel.h5

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./
          # Specify the path to the model relative to the source directory
          args: --model_path=main/MyModel\(1\).h5  # Adjust this based on your directory structure

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
