name: Deploy ML Model to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: vetion-app-424904
  SERVICE: model-vetion-app
  REGION: asia-southeast2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download ML Model
        run: |
          mkdir -p model
          wget -q https://github.com/VetionTeam/Vetion-Model/raw/main/MyModel%20%281%29.h5 -O model/MyModel.h5

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
          source: ./

      - name: Show Deployment Output
        run: echo ${{ steps.deploy.outputs.url }}
